version: '3.8'

services:
  # Method 1: Using environment variables
  jplaw2epub-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Set CORS origins (comma-separated list)
      - CORS_ORIGINS=https://example.com,https://app.example.com
      # Alternative: Allow all origins for development
      # - CORS_ORIGINS=*
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Method 2: Using command-line arguments
  jplaw2epub-api-args:
    build: .
    ports:
      - "8081:8080"
    command: ["-cors-origins", "https://example.com,https://app.example.com"]
    restart: unless-stopped
    profiles:
      - args

  # Example: Development setup with all origins allowed
  jplaw2epub-api-dev:
    build: .
    ports:
      - "8082:8080"
    command: ["-cors-origins", "*"]
    restart: unless-stopped
    profiles:
      - dev

  # Example: Custom port and CORS
  jplaw2epub-api-custom:
    build: .
    ports:
      - "9000:9000"
    command: ["-port", "9000", "-cors-origins", "https://custom.example.com"]
    restart: unless-stopped
    profiles:
      - custom